### ISSUE TITLE
The dnsPolicy cannot be defined for the DatadogAgent in v2alpha1

### ISSUE THREAD

**Issue by 13013SwagR** [DataDog/datadog-operator#1144]
**Output of the info page (if this is a bug)**
```
None
```

**Describe what happened:**
The dnsPolicy cannot be defined for the DatadogAgent since v2alpha1.

**Describe what you expected:**
The dnsPolicy to be available as an override in `spec.override.[key].dnsPolicy` 
or the `dnsPolicy` to be set to `ClusterFirstWithHostNet` when setting `spec.override.[key].hostNetwork`
like it used to be on the [HelmChart install](https://github.com/DataDog/helm-charts/blob/ea26a30a806dc12bf9fb3b068836c0e2a06a051b/charts/datadog/templates/daemonset.yaml#L96-L99)

**Steps to reproduce the issue:**
See https://github.com/DataDog/datadog-operator/blob/main/docs/configuration.v2alpha1.md#override

**Additional environment details (Operating System, Cloud provider, etc):**
We have a custom dns setup and we need to set `dnsPolicy` to `ClusterFirstWithHostNet` like we currently have with the Agent Helm Chart installation.

**Comment by 13013SwagR** [comment]
Hello @khewonc ,

I urge reconsidering the classification of the missing dnsPolicy in v2alpha1 as a mere feature request. This functionality was present in v1alpha1 and is documented [here](https://github.com/DataDog/datadog-operator/blob/main/apis/datadoghq/v1alpha1/datadogagent_conversion_agent.go#L176). Its absence in v2alpha1 is a regression that disrupts established configurations and impacts critical network operations.

Previously, users could set dnsPolicy explicitly or rely on automatic settings tied to hostNetwork. Removing this without a clear alternative affects those of us with custom DNS setups transitioning from Helm or v1alpha1.

Please consider this a bug due to its significant impact on functionality and user experience. Addressing this would help ensure consistency and reliability for configurations across versions.

Thank you for your attention to this matter.

**Comment by Eokye** [comment]
@13013SwagR Thanks for bringing this to our attention. The issue has been resolved in the 1.8 release.

**Comment by 13013SwagR** [comment]
Thanks, I'll test!
