### ISSUE TITLE
Dead link in docs datadog-operator/docs /configuration.v2alpha1.md

### ISSUE THREAD

**Issue by JasBonker** [DataDog/datadog-operator#1176]
**Describe what happened:**
On the page 'https://github.com/DataDog/datadog-operator/blob/main/docs/configuration.v2alpha1.md' clicking on '* Manifest with Logs, APM, and metrics collection enabled.' forwards you to a non existing page/file.

**Describe what you expected:**
I was expected to be forwarded to 'https://github.com/DataDog/datadog-operator/blob/main/examples/datadogagent/v2alpha1/datadog-agent-logs-apm.yaml' without getting a 404 error.
![image](https://github.com/DataDog/datadog-operator/assets/86851707/9a66b861-d164-4ef7-8312-4ec13521f49b)

**Steps to reproduce the issue:**
Go to 'https://github.com/DataDog/datadog-operator/blob/main/docs/configuration.v2alpha1.md' and click on '* Manifest with Logs, APM, and metrics collection enabled.'

**Additional environment details (Operating System, Cloud provider, etc):**
N/A

**Comment by khewonc** [comment]
Hi, thanks for reporting this. We'll have a fix for those links in https://github.com/DataDog/datadog-operator/pull/1199

**Comment by khewonc** [comment]
Closing this since it's been fixed in #1199
