### ISSUE TITLE
DataDogMonitor CRD is missing the renotifyStatuses field

### ISSUE THREAD

**Issue by 0robustus1** [DataDog/datadog-operator#1216]
Currently the CRD of the DatadogMonitor resource is missing the `renotifyStatuses` field that can be configured on a monitor.
Similar to https://github.com/DataDog/datadog-operator/issues/833 we would ask you to add support for the field.

In general: What is the expectation regarding field coverage between the Monitor (REST) API and the custom resource in the operator? Should all fields be supported?

**Comment by Eokye** [comment]
Hey @0robustus1! This issue has now been solved in the new 1.8 release. Thanks for bringing it to our attention.
