### ISSUE TITLE
2.0 version published on artifact hub?

### ISSUE THREAD

**Issue by Scalahansolo** [DataDog/datadog-operator#1447]
Hey Datadog. Im pretty confused about the version schema / release process yall are using for the operator. Here on Github releases, it looks like 1.8 is the most recent release. However, over at https://artifacthub.io/packages/helm/datadog/datadog-operator, there is a 2.0.0 and 2.0.1 and even some other 1.8.X versions. What the is the source of truth for which version are the "latest" and most stable versions? 

The actual docs over on Datadog are also very confusing as they don't line up with things here all the time.

I've also noticed there is https://github.com/DataDog/helm-charts/blob/main/charts/datadog-operator/values.yaml (in a different repo) as well as the configs here (https://github.com/DataDog/datadog-operator/blob/main/docs/configuration.v2alpha1.md) and they don't line up. 

As a separate issue, I have an issue I'm trying to work through with library injection not working, and the fact that all your docs are spread across various repos and there is no clear source of truth is super frustrating.

**Comment by vboulineau** [comment]
Hello @Scalahansolo,

Your reference in ArtifactHub point to the `datadog-operator` Helm chart. This is used to install the `datadog-operator` itself, and as usual with Helm charts, there are two versions:
- The Helm chart version (2.0.1) (chart version)
- The version of the package application (1.8) (application version, usually the Docker image tag).

The configuration of the **Datadog Agent** deployed by the Datadog Operator is in the `DatadogAgent` CR and the reference with all settings is indeed: https://github.com/DataDog/datadog-operator/blob/main/docs/configuration.v2alpha1.md

The values you found at https://github.com/DataDog/helm-charts/blob/main/charts/datadog-operator/values.yaml are the `datadog-operator` Helm chart values, hence used to configure `datadog-operator` Helm chart installation only.

If you have a specific issue with library injection, it's better to open a dedicated issue.

**Comment by Scalahansolo** [comment]
I'll open a dedicated issue for that. I have also reached out to Support because I have injection setup identically in two different clusters but it's only working in one. I don't know if your able to see support cases, but my case # is 1870765. 

Beyond that issue though... Am I wrong to think that all these different places for how to use the operator and keep it updated is super confusing? It really feels like the docs on datadog proper could be updated to clarify all of this.
