### ISSUE TITLE
Add the secrets helper to datadog-operator

### ISSUE THREAD

**Issue by jessecollier** [DataDog/datadog-operator#148]
The datadog operator should have the default secrets manager helper baked into the docker image like the datadog agent. This would allow to easily use the same secret manager for operator, cluster-agent and agent in one shot.

Further, the operator should be easily configured to to support mounting a secret volume and configure the commands + args variables with the defaults. The user should only have to supply a `secretName` value and perhaps a flag to enable secrets to be read from file.

https://github.com/DataDog/datadog-agent/blob/master/Dockerfiles/agent/secrets-helper/readsecret.py

**Comment by ahmed-mez** [comment]
Hi @jessecollier , thank you for opening this issue.

The datadog operator supports the [secret backend feature](https://github.com/DataDog/datadog-operator/blob/master/docs/secret_management.md#3-use-the-secret-backend-feature) but it's true that we don't ship a read secret helper.
I believe this is a valid feature request, and we'll make sure to include in the next datadog operator release (`v0.5.0`), in the meantime you can add your own secret decryption script as documented [here](https://github.com/DataDog/datadog-operator/blob/master/docs/secret_management.md#how-deploy-the-datadog-operator-with-the-secret-backend-activated).

Note: We don't have Python in the operator docker image, it would probably be a shell script calling go code like we do for [the cluster agent](https://github.com/DataDog/datadog-agent/blob/master/Dockerfiles/cluster-agent/readsecret.sh)

Thanks!
