### ISSUE TITLE
Missing download link on "Getting Started" page

### ISSUE THREAD

**Issue by hitsumabushi845** [DataDog/datadog-operator#188]
**Describe what happened:**
Although I've checked [Getting Started](https://github.com/DataDog/datadog-operator/blob/master/docs/getting_started.md) page, the chart download link has been disabled.
The link( https://github.com/DataDog/datadog-operator/releases/latest/download/datadog-agent-with-operator.tar.gz ) returns "Not Found". I'd sought [Releases page](https://github.com/DataDog/datadog-operator/releases) but I couldn't find which file is proper one...

**Describe what you expected:**
Fix the download link on the document if you can.
If this issue is caused by my misunderstanding, please let me know correct way.

**Comment by randallt** [comment]
I've run into the same thing. Can't figure out how to install using your instructions. The first few steps are wrong.

**Comment by hitsumabushi845** [comment]
I've checked latest Getting Started page and it had been updated by the commit https://github.com/DataDog/datadog-operator/commit/f5a4f502d409c096d0c8873681dba304b77db543#diff-7627439dcd69d95a42bb123ac4cfb7682f86da5d6aee037206d9857459906243.
So the issue I raised here is solved, so I close this issue.
Thanks:)
