### ISSUE TITLE
I can't use the chart as a dependency

### ISSUE THREAD

**Issue by batazor** [DataDog/datadog-operator#201]
**Output of the info page (if this is a bug)**

I created a new chart by specifying datadog-operator as a dependency to describe `kind: DatadogAgent` in `templates` of my chart.

**Describe what happened:**

Unfortunately, when I try to run it I get

```
> helm upgrade datadog-operator ops/Helm/addons/datadog --install --wait --namespace=datadog-operator --create-namespace=true --set apiKey=$API_KEY

> Release "datadog-operator" does not exist. Installing it now.
> Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "DatadogAgent" in version "datadoghq.com/v1alpha1"
```

**Describe what you expected:**

successful installation

**Steps to reproduce the issue:**

[my GitLab CI job](https://gitlab.com/shortlink-org/shortlink/-/jobs/947813474)

**Additional environment details (Operating System, Cloud provider, etc):**

**Comment by levan-m** [comment]
Bulk resolving DatadogAgent `v1alpha1` issues.
