### ISSUE TITLE
Publish linux/arm64 images

### ISSUE THREAD

**Issue by DWSR** [DataDog/datadog-operator#202]
As a cluster operator of an ARM cluster (i.e. AWS Graviton or Raspberry Pis), I'd like to be able to use the Datadog Operator instead of the Helm Chart for Agent installation to avoid the requirement of using Helm.

I quickly changed `GOARCH=amd64` to `GOARCH=arm64` in the `Dockerfile` to see if the operator compiles and it does, so this should only require rigging up the CI pipelines to build and publish the images themselves.

**Comment by clamoriniere** [comment]
Hi @DWSR 

Thanks for opening this issue. We are working on improving our CI to build the `datadog/operator` image for more OS and ARCH and generate a multi-arch images (like we do for the `datadog/agent` image).
It should be available before the end of Q1.

We will update this issue when it is done.
