### ISSUE TITLE
How do we customize the Admission Controller webhook timeout?

### ISSUE THREAD

**Issue by diranged** [DataDog/datadog-operator#220]
**Describe what happened:**
The Admission Controller MutatingWebhookConfiguration is created with a 30s timeout. I would like to be able to lower this down to 1 or 2 seconds. We ran into an issue over the weekend where a mistake in a NetworkPolicy caused the APIServer->DatadogOperator API calls to fail. They took 30s to time out, which then slowed the entire APIServer down. That ultimately lead to a high rate of registration failures for new nodes joining our clusters. All of our other WebhookConfigurations have low timeouts set.

```
Name:         datadog-webhook
Namespace:    
Labels:       <none>
Annotations:  <none>
API Version:  admissionregistration.k8s.io/v1
Kind:         MutatingWebhookConfiguration
Metadata:
...
  Resource Version:  42875294
  Self Link:         /apis/admissionregistration.k8s.io/v1/mutatingwebhookconfigurations/datadog-webhook
  UID:               deda10ff-ca41-4e2b-bf3c-ed02bac00af6
Webhooks:
  Admission Review Versions:
    v1beta1
  Client Config:
     Ca Bundle:  LS0t...
    Service:
      Name:        datadog-admission-controller
      Namespace:   datadog-operator
      Path:        /injecttags
      Port:        443
  Failure Policy:  Ignore
  Match Policy:    Exact
  Name:            datadog.webhook.tags
  Namespace Selector:
  Object Selector:
    Match Expressions:
      Key:       admission.datadoghq.com/enabled
      Operator:  NotIn
      Values:
        false
  Reinvocation Policy:  Never
  Rules:
    API Groups:
      
    API Versions:
      v1
    Operations:
      CREATE
    Resources:
      pods
    Scope:          *
  Side Effects:     None
  Timeout Seconds:  30
Events:             <none>
```

**Describe what you expected:**
I would like to be able to configure the timeout here and lower it to meet our operational needs. This configuration is not exposed currently (as far as I can tell) in the Datadog Operator or DatadogAgent CRD.

**Additional environment details (Operating System, Cloud provider, etc):**

Datadog Operator v0.4.0, EKS Kubernetes 1.18

**Comment by ahmed-mez** [comment]
Hi @diranged, thank you for opening the issue and sorry for the trouble!

Configuring the Mutating Webhook timeout is not supported currently,  30s is the default value set by Kubernetes ([see here](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers)) 

The change must be first done at the [Cluster Agent level ](https://github.com/DataDog/datadog-agent/blob/e081bed84866686eeab56a98da5ff9b4b9f03ded/pkg/clusteragent/admission/util.go#L69) to expose the new config, once done we can add a dedicated field for it in the DatadogAgent  CRD.

Please don't hesitate to [contact our support team ](https://docs.datadoghq.com/help/) to open a feature request. 

Thanks!

**Comment by diranged** [comment]
@ahmed-mez Thanks for the fast response. Are you suggesting that I open a ticket in the other repo to track this as a feature request? Or should we make this request through our account reps?

**Comment by ahmed-mez** [comment]
I'd recommend making the feature request by contacting our support team. Additionally, you can open an issue in the datadog-agent repo as well, as it might be useful for the community. Thanks!

**Comment by ahmed-mez** [comment]
Answered in https://github.com/DataDog/datadog-agent/issues/7387

Thanks!
