### ISSUE TITLE
Dashboard CRD?

### ISSUE THREAD

**Issue by Geethree** [DataDog/datadog-operator#399]
I see a old issue around various CRDs here (https://github.com/DataDog/datadog-operator/issues/4), but I'd love to have a CRD for dashboards. 

Is this on a roadmap anywhere? And/or anyway to help assist in bringing this to reality?

Grafana-operator might have some good inpiration
https://github.com/grafana-operator/grafana-operator/blob/master/documentation/dashboards.md

**Comment by nnordrum** [comment]
came here to open this issue; would be really nice to have!

**Comment by cmotta2016** [comment]
We're starting the project to migrate our monitoring stack to Datadog and this feature would help a lot.

**Comment by zalbiraw** [comment]
Kibana and Grafana both offer this. It would be nice if I can manage my dashboard as a CRD or offer a way to import dashboards as configmaps like keycloak do with their realms.

**Comment by dlorent** [comment]
Agreed, this would also be very helpful in our setup where we already are using monitor crds.

**Comment by 0xStarcat** [comment]
Would love this! right now our monitoring-as-code is split between these CRDs and Terraform :(

**Comment by Geethree** [comment]
Meh. It’s been 627 days and no response ;)

**Comment by gonmmarques** [comment]
+1

**Comment by dreinhardt-terminus** [comment]
+1

**Comment by yurymkomarov** [comment]
+1

**Comment by celenechang** [comment]
Hi @Geethree and all, thank you for making this request. This feature has been released (in Preview) with Operator 1.9.0. Documentation can be found [here](https://github.com/DataDog/datadog-operator/blob/main/docs/datadog_dashboard.md). Note that `DatadogDashboard` manifests can be copied/exported from a new option available in the Configure menu of custom dashboards.

![Image](https://github.com/user-attachments/assets/d5af9426-5ea9-409a-8fdf-fb393fd69f50)
