### ISSUE TITLE
New feature: allow configuring security context on cluster agent

### ISSUE THREAD

**Issue by praseodym** [DataDog/datadog-operator#415]
It's currently possible to customize the security context for agent pods through the `agent.config.securityContext.*` setting, but this option is not available for the cluster agent pod. This is a feature request to allow configuring the security context on cluster agents too.

For Kubernetes deployments with strict pod security policies, customizing the security context is required due to the image not specifying that it will run as user 0, causing pod creation to fail with `Error: container has runAsNonRoot and image will run as root`.

**Comment by clamoriniere** [comment]
Hi @praseodym,

Thanks for opening this issue, I'm adding this issue to our backlog.

IMO the cluster-agent doesn't require to run as root. So if we can apply by default the proper level of permission to the cluster-agent container it should also solve the issue.

could you share with use, what will be the security context that you want to apply to the cluster-agent?

**Comment by praseodym** [comment]
The cluster agent runs as root by default, the image doesn't specify that it should run as another user:

```
$ docker run --rm -it --entrypoint /bin/id gcr.io/datadoghq/cluster-agent:1.13.1
uid=0(root) gid=0(root) groups=0(root)
```

To fix that I'd need to set the `securityContext.runAsUser` property to the correct uid. If the image does need to run as root, I'd need to set `securityContext.runAsNonRoot` to `false`.

Another solution would be to update the cluster agent Docker image to use a numeric uid greater than 0 (i.e. non-root) as its `USER`. It needs to be numeric because usernames can resolve to uid 0, and [kubelet explictly checks this](https://github.com/kubernetes/kubernetes/blob/c1e69551be1a72f0f8db6778f20658199d3a686d/pkg/kubelet/kuberuntime/security_context_others.go#L49).
