### ISSUE TITLE
Automatic sidecar injection of datadog agent (for eg running on AWS Fargate)

### ISSUE THREAD

**Issue by mcuelenaere** [DataDog/datadog-operator#416]
When running containers on AWS Fargate, there is no possibility to run datadog-agent as a DaemonSet. The only possible way (AFAIK) is by adding a sidecar container to the pod.

It would be useful if datadog(-operator) would have a feature where it can (optionally) automatically inject datadog-agent containers into pods (similar to what eg Istio or AWS AppMesh do).

Is this feature on the roadmap somewhere?

**Comment by clamoriniere** [comment]
Hello @mcuelenaere 

Yes we already have this feature in our roadmap. It will be a little bit different from what you propose. We plan to use the [admission-controller ](https://docs.datadoghq.com/agent/cluster_agent/admission_controller/) already present in the Datadog cluster-agent to inject an agent container as a sidecar.

**Comment by comjf** [comment]
Hi sorry to jump in but is this to say that currently AWS Fargate cannot run this datadog-operator? (I run a fargate only cluster)

I've gone ahead and setup the dd agent via sidecar injection method, as [documented](https://docs.datadoghq.com/integrations/eks_fargate/), but I'm still missing a lot of what this controller has to offer, right? (k8s event metrics for one?)

**Comment by lteixeira-dock** [comment]
Hi,

I would like receive when this feature is available, please

Thank you!

**Comment by pmcenery-bl** [comment]
Hi.

Is there any chance of some movement on this feature? We could really make use of it.

Many thanks!

**Comment by adel121** [comment]
Hello @pmcenery-bl, @lteixeira-dock 

This feature has just been release in version 7.52 of the agent.

Refer to the readme [here](https://github.com/DataDog/datadog-agent/blob/main/pkg/clusteragent/admission/mutate/agent_sidecar/README.md) for more details.

**Comment by levan-m** [comment]
This was added to the Operator in v1.7.0
https://github.com/DataDog/datadog-operator/pull/1207
https://github.com/DataDog/datadog-operator/pull/1209
