### ISSUE TITLE
DD_SITE exported in datadog-operator helm template not heeded in datadog-operator code

### ISSUE THREAD

**Issue by haraldsk** [DataDog/datadog-operator#419]
The [helm values](https://github.com/DataDog/helm-charts/blob/main/charts/datadog-operator/values.yaml#L18-L24) file in datadog-operator helm chart exposes the `site` value as a way to set the $DD_SITE variable. This is sent to the operator POD. 

However the datadog-agent configuration code in [InitDatadogClient](https://github.com/DataDog/datadog-operator/blob/eea7b7edb65d80a875328c677644e397d8d9b0a1/pkg/datadogclient/client.go#L27) only supports $DD_URL.

This is very confusing for people using a non-us site like datadoghq.eu .

**Comment by haraldsk** [comment]
Also reported here: https://github.com/DataDog/datadog-operator/issues/623

**Comment by celenechang** [comment]
Hi @haraldsk , this was fixed in https://github.com/DataDog/datadog-operator/pull/838 and will be part of 1.1.0 . Apologies and thanks for your patience.
