### ISSUE TITLE
Any eta on Event Monitor type?

### ISSUE THREAD

**Issue by jbiskur** [DataDog/datadog-operator#421]
**Describe what happened:**
When adding a monitor like the "error rate for latest deployment" the event type alert is not supported. I have tried with all types, query, metric, service and composite

**Describe what you expected:**
A monitor created similar to the "suggested" monitors for error rate on latest deployment

**Steps to reproduce the issue:**
add an alert with
```events('tags:deployment_analysis,env:{{ $.Values.environment }},service:{{ $serviceName }}-{{ $value }} priority:all').rollup('count').last('15m') > 0```
this is returned
```
error validating monitor: 400 Bad Request: {"errors": ["The value provided
      for parameter ''query'' is invalid"]}
```

**Additional environment details (Operating System, Cloud provider, etc):**
Operator v0.7.6

**Comment by clamoriniere** [comment]
Hi. @jbiskur 

thanks for opening this issue. Indeed `Event` monitor type is not yet supported.
We already have this feature request in our roadmap and should land the Operator in a near feature.

Regards
Cedric

**Comment by celenechang** [comment]
Hello @jbiskur , event monitor types (and many others) will be supported in the next Datadog Operator version (https://github.com/DataDog/datadog-operator/pull/428).
