### ISSUE TITLE
Datadog Operator on Redhat Marketplace 

### ISSUE THREAD

**Issue by bheemreddy181** [DataDog/datadog-operator#495]
Can datadog update/release the latest operator on Redhat Marketplace as we are facing issues with upgrading the redhat instance 

![MicrosoftTeams-image (14)](https://user-images.githubusercontent.com/101338506/168922047-1f24c1d5-a612-4450-a041-9b5f36afc703.png)

**Comment by vboulineau** [comment]
Hey @bheemreddy181,

We've published Operator `0.8.0` to RedHat Marketplace, it should remove this limitation. Feel free to re-open if you still face the issue.

**Comment by bheemreddy181-zz** [comment]
How can we track the release into Redhat environments?

**Comment by vboulineau** [comment]
Normally it's shortly after the tag publication on GitHub, but it took a bit more time for `0.8` as there were some changes on the validation workflow on RedHat side.

You can check the version in your OpenShift Cluster -> OperatorHub.

You can also check this repository (https://github.com/redhat-openshift-ecosystem/redhat-marketplace-operators/tree/main/operators/datadog-operator-certified-rhmp), which is where we push new versions for Marketplace.

**Comment by bheemreddy181-zz** [comment]
Thanks for the inputs here
