### ISSUE TITLE
[Helm] Cannot install operator via helm into EKS cluster

### ISSUE THREAD

**Issue by geekflyer** [DataDog/datadog-operator#565]
I tried installing the operator into an EKS cluster via: 
```
helm install datadog-operator datadog/datadog-operator --namespace datadog
```

which fails with:

```
➜  pre-commit git:(main) ✗ helm install datadog-operator datadog/datadog-operator --namespace datadog
Error: INSTALLATION FAILED: template: datadog-operator/charts/datadog-crds/templates/datadoghq.com_datadogmonitors_v1beta1.yaml:1:41: executing "datadog-operator/charts/datadog-crds/templates/datadoghq.com_datadogmonitors_v1beta1.yaml" at <semverCompare "<=21" .Capabilities.KubeVersion.Minor>: error calling semverCompare: Invalid Semantic Version
```

EKS version:

```
➜  pre-commit git:(main) ✗ k version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-03T13:36:49Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.10-eks-84b4fe6", GitCommit:"cc6a1b4915a99f49f5510ef0667f94b9ca832a8a", GitTreeState:"clean", BuildDate:"2022-06-09T18:24:04Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.24) and server (1.22) exceeds the supported minor version skew of +/-1
```
Same problem with EKS 1.21.

helm version: 
```
➜  pre-commit git:(main) ✗ helm version                                                                                                    
version.BuildInfo{Version:"v3.9.1", GitCommit:"a7c043acb5ff905c261cfdc923a35776ba5e66e4", GitTreeState:"clean", GoVersion:"go1.18.4"}
```

**Comment by CharlyF** [comment]
@geekflyer would you mind trying the change from this [PR](https://github.com/DataDog/helm-charts/pull/703)?
From my testing it should work but I want to make sure we fix your issue too.

**Comment by lucasheringer** [comment]
I know this is closed but I'm still facing this trying to install datadog-operator chart on a EKS running Kubernetes v1.22:
`helm install datadog-operator datadog/datadog-operator --set apiKey=***** --set appKey=****** --set datadogMonitor.enabled=true --debug
install.go:178: [debug] Original chart version: ""
install.go:195: [debug] CHART PATH: /Users/lucasheringer/Library/Caches/helm/repository/datadog-operator-0.8.5.tgz

Error: INSTALLATION FAILED: template: datadog-operator/charts/datadog-crds/templates/datadoghq.com_datadogmonitors_v1beta1.yaml:1:41: executing "datadog-operator/charts/datadog-crds/templates/datadoghq.com_datadogmonitors_v1beta1.yaml" at <semverCompare "<=21" .Capabilities.KubeVersion.Minor>: error calling semverCompare: Invalid Semantic Version
helm.go:84: [debug] template: datadog-operator/charts/datadog-crds/templates/datadoghq.com_datadogmonitors_v1beta1.yaml:1:41: executing "datadog-operator/charts/datadog-crds/templates/datadoghq.com_datadogmonitors_v1beta1.yaml" at <semverCompare "<=21" .Capabilities.KubeVersion.Minor>: error calling semverCompare: Invalid Semantic Version
INSTALLATION FAILED
main.newInstallCmd.func2
	helm.sh/helm/v3/cmd/helm/install.go:127
github.com/spf13/cobra.(*Command).execute
	github.com/spf13/cobra@v1.4.0/command.go:856
github.com/spf13/cobra.(*Command).ExecuteC
	github.com/spf13/cobra@v1.4.0/command.go:974
github.com/spf13/cobra.(*Command).Execute
	github.com/spf13/cobra@v1.4.0/command.go:902
main.main
	helm.sh/helm/v3/cmd/helm/helm.go:83
runtime.main
	runtime/proc.go:250
runtime.goexit
	runtime/asm_amd64.s:1571`

**Comment by RobertKeyser** [comment]
Is this perhaps because the latest version of the chart is 0.8.5 (pre-fix) still? Does there need to be a new release so the version gets fixed?
