### ISSUE TITLE
datadog-operator-manager OOMKill

### ISSUE THREAD

**Issue by hoeggi** [DataDog/datadog-operator#569]
After installing the operator in openshift via OLM, the memory limit of the datadog-operator-manager pod/deployment is set to `memory: 250Mi` 

This causes an OOMKill crashloop for me. I was able to work around the problem by manually setting the limit to `512Mi` in the deployment but since this is owned by the CSV it regularly gets reverted.

Screenshot of the pod memory usage over ~20min :
![Screenshot from 2022-07-25 09-23-21](https://user-images.githubusercontent.com/1011509/180721349-1c9cac82-25d1-4ce6-85c5-fc104185c1c2.png)

Operator Verions: 0.8.1
Openshift Version: 4.8.23

**Comment by clamoriniere** [comment]
Hi @hoeggi 

OLM allow you to configure override part of the Operator configuration thanks to the `Subscription` resource. You can change how much CPU and Memory are allocated to each Operator pod: https://github.com/DataDog/datadog-operator/blob/main/docs/installation.md#override-default-operator-configuration

It should solve the issue.
