### ISSUE TITLE
Better documentation and examples for DatadogMonitor CRD

### ISSUE THREAD

**Issue by red8888** [DataDog/datadog-operator#572]
I really want to use this, but the documentation is all but non existent.

I can't just export a monitor as json and convert it to yaml because the CRDs fields are totally different. So its up to me to read the source code and try to figure this out myself? https://github.com/DataDog/datadog-operator/blob/87632a90440e48ec0c7ba1015e3371345bb89cd1/apis/datadoghq/v1alpha1/datadogmonitor_types.go#L62

There should be a clear mapping of UI field names to CRD names. Maybe in an example here or something: https://github.com/DataDog/datadog-operator/tree/87632a90440e48ec0c7ba1015e3371345bb89cd1/examples/datadogmonitor

There should be something like this so its obvious what field maps to what UI field
```
  options:
    # Evaluation options: Before evaluating new groups, wait X seconds
    evaluationDelay: 303
```

**Comment by levan-m** [comment]
There is a documentation in the CRD itself which is getting installed in the cluster, e.g. one for your example
https://github.com/DataDog/datadog-operator/blob/87632a90440e48ec0c7ba1015e3371345bb89cd1/config/crd/bases/v1/datadoghq.com_datadogmonitors.yaml#L74-L80

The CRD fields map to to Datadog API Go client, which calls the Datadog public API documented here
https://docs.datadoghq.com/api/latest/monitors/#create-a-monitor
