### ISSUE TITLE
Possibly Incorrect Default Unix Socket Path

### ISSUE THREAD

**Issue by daviddyball** [DataDog/datadog-operator#585]
**Describe what happened:**
Provisioning new `DatadogAgent` resources with `spec.agent.apm.unixDomainSocket.enabled: true` creates a socket under `/var/run/datadog/apm.sock`, which contradicts most client libraries default lookup path of `/var/run/datadog/apm.socket` (`socket` not `sock`).

**Describe what you expected:**
I expected the `DatadogAgent` to provision using the correct socket path name

**Steps to reproduce the issue:**
Provision any simple `DatadogAgent` `v1alpha1` resource.

**Additional environment details (Operating System, Cloud provider, etc):**

`datadog-operator` version `0.8.1`.

**Comment by chrispsplash** [comment]
Indeed, the [datadog cluster agent notes explicitly state the default path ends with `apm.socket`](https://github.com/DataDog/datadog-agent/blob/85a8590c31b8ec68b256fcfc1263264c0dcaef02/pkg/config/config_template.yaml#L2457)

**Comment by jcogilvie** [comment]
For what it's worth, the admission controller injects a value which matches the operator.  Using it might simplify your configuration.

**Comment by levan-m** [comment]
Hello, sorry for not getting to the issue on time. Operator `v0.x` is no longer supported and we recommend migrating to most recent version of `v1.x`. 

Please open a new issue if there is anything blocking migration or you experience same issue in `v1.x`.
