### ISSUE TITLE
Krew plugin is unavailable on darwin/arm64

### ISSUE THREAD

**Issue by ghostsquad** [DataDog/datadog-operator#599]
Please add support for the `datadog` krew plugin on darwin/arm64 (M1 Macs)

**Comment by CharlyF** [comment]
Hey there - As part of the GA of the Datadog Operator, we also fixed the [plugin release](https://github.com/DataDog/datadog-operator/releases/tag/v1.0.2) which now supports ARM.
I am going to close this for now but feel free to reach out if you have anymore questions.
