### ISSUE TITLE
Feature request: Annotations for serviceAccounts

### ISSUE THREAD

**Issue by chrispsplash** [DataDog/datadog-operator#600]
We, as most EKS users do, rely on [IRSA roles](https://docs.aws.amazon.com/emr/latest/EMR-on-EKS-DevelopmentGuide/setting-up-enable-IAM.html) to grant cloud perms to K8s apps.  An `annotation` on the `serviceAccount` is required to link the running app to an IAM role.

It would be lovely to have this [serviceAccountAnnotations feature](https://github.com/DataDog/helm-charts/tree/main/charts/datadog#:~:text=agents.rbac.serviceAccountAnnotations) so EKS users can migrate from the datadog Helm chart to the excellent datadog-operator 🙏 

**Additional environment details (Operating System, Cloud provider, etc):**
AWS, EKS, K8s 1.20

**Comment by EdwardOlmos** [comment]
I've come across this issue as well and implementing this feature will improve my current workflow for getting the Datadog Operator to work on EKS.

I believe many other users would also benefit from this enhancement, so it would be fantastic to see it implemented in the Operator. Thanks again for raising this, and fingers crossed that the Datadog team takes it into consideration for future updates!

**Comment by bkalcho** [comment]
+1

This is very important feature, as it is crucial when enabling external checks. It should be given higher priority. Also check if feasible implementation of support for [EKS Pod Identities](https://aws.amazon.com/blogs/aws/amazon-eks-pod-identity-simplifies-iam-permissions-for-applications-on-amazon-eks-clusters/) as it is replacement for IRSA.
Some of requirements for EKS Pod Identities: https://docs.aws.amazon.com/eks/latest/userguide/pod-id-minimum-sdk.html

**Comment by choco-nishant** [comment]
+1

This feature is also essential for us from a security perspective to enable Database Monitoring with AWS RDS. Currently, we have to use a username and password, but having this feature will help us use [IAM authentication](https://docs.datadoghq.com/database_monitoring/guide/managed_authentication/?tab=eks).

**Comment by levan-m** [comment]
Hello, is this request for supporting [this](https://github.com/DataDog/helm-charts/blob/e1ec85127de74c8b876eef6a81bb1579d17b49bf/charts/datadog/values.yaml#L1492-L1493) configuration (for Agent, DCA, CLC) from Helm chart in the Operator?

```yaml
    # agents.rbac.serviceAccountAnnotations -- Annotations to add to the ServiceAccount if agents.rbac.create is true
    serviceAccountAnnotations: {}
```

**Comment by jamesduffy** [comment]
> Hello, is this request for supporting [this](https://github.com/DataDog/helm-charts/blob/e1ec85127de74c8b876eef6a81bb1579d17b49bf/charts/datadog/values.yaml#L1492-L1493) configuration (for Agent, DCA, CLC) from Helm chart in the Operator?
> 
> ```yaml
>     # agents.rbac.serviceAccountAnnotations -- Annotations to add to the ServiceAccount if agents.rbac.create is true
>     serviceAccountAnnotations: {}
> ```

Yes, having support for that configuration in the operator would fix it for us.
