### ISSUE TITLE
Resource requests and limits in DatadogAgent CRD v2

### ISSUE THREAD

**Issue by jcogilvie** [DataDog/datadog-operator#669]
Is there a prescribed way to set resource requests and limits on the v2alpha1 resources?  Or is this expected to be handled for us by some internal logic?

**Comment by vboulineau** [comment]
Hey @jcogilvie,

Resources can be set through the `override` section for any component, for instance for node Agent: https://github.com/DataDog/datadog-operator/blob/main/apis/datadoghq/v1alpha1/testdata/all.expected.yaml#L169-L171

**Comment by pellizzetti** [comment]
The previously link is pointing to the main branch, which has been changed and no longer contains an example of how to configure resources. Luckily, the CRD documentation shows how to perform this [configuration](https://github.com/DataDog/datadog-operator/blob/0b5857932b1735bf493f5e5d8ff0746cb98e44aa/docs/configuration.v2alpha1.md#override).
