### ISSUE TITLE
Service Level Objectives CRD

### ISSUE THREAD

**Issue by rajatparida86** [DataDog/datadog-operator#684]
I see in [this old ticket](https://github.com/DataDog/datadog-operator/issues/4) a request for Datadog operator handling custom resources (e.g. Monitor, Dashboard etc). I also see that [support for monitors has been added recently](https://github.com/DataDog/datadog-operator/tree/main/examples/datadogmonitor). Thanks for that feature.

I wanted to understand if there is a plan to also support a CRD for SLOs in the operator roadmap? SLOs are quite important for us and we would love to maintain SLO configuration close to rest of our infrastructure configuration (provisioned through kube manifests).

Any feedback here is highly appreciated.

**Comment by CharlyF** [comment]
Hello @rajatparida86 - Thanks for that feature request.
SLOs are one of the resources we are considering adding a CRD for! Beyond the ease of use in terms of provisioning, are there use cases that you could benefit from?
Thinking about how the Datadog Operator could update the upstream SLO's metadata (status correction) under certain conditions for it to be more accurate (rolling updates, specific events etc).

Thanks!

**Comment by rajatparida86** [comment]
@CharlyF Thanks a lot for your quick reply

Apart from ease of creating and maintaining SLOs, the other aspects that we are focusing on:
- Minimise unwanted alerts/incidents by preventing misconfiguration of SLOs and their related monitors. We want to have 4 eye principle applied
- Making SLOs a standard for all our services - each service that we create has SLOs and alerts attached to them
- Enabling a standard configuration (e.g. standard naming, set of tags, etc) of SLOs throughout our service landscape

We would be quite keen to join forces and speed up the development of this feature. What would be the right way to move this forward?

**Comment by CharlyF** [comment]
That sounds good - Could you send over an email at c@datadoghq.com and I will include our product team in the thread to discuss expectations and how we can collaborate.
I am going to keep this issue for future updates on this project, should new users want to express interest, they can feel free to add an emoji reacting to @rajatparida86's initial message.

**Comment by dlydiard** [comment]
Our organization also has demand for this use case. We want to be able to:

- Automate the creation of DataDog SLOs via GitOps (ArgoCD) via CRDs.
- Create a reusable standard set of SLO CRDs for our services that can be templated via HELM.

**Comment by jurabek** [comment]
Hey @CharlyF I am not sure what was outcome of the discussion with @rajatparida86 by email, however we are still looking forward to use `datadog-operator` for defining our SLO's, we would appreciate if we can collaborate on #807 and make it live, that we could use it in our cluster.

**Comment by gonmmarques** [comment]
+1
