### ISSUE TITLE
Request documentation improvement or breaking change on the release notes about upgrades

### ISSUE THREAD

**Issue by nicolodallavalentinaclearscore** [DataDog/datadog-operator#754]
I would like to request documentation improvement on README.md regarding how to install/upgrade between Major releases and also mention any breaking changes on each release note. Please note at the moment this information is present on just the helm charts but would be great to have it at least mentioned in 2 lines like here. This improvement can save team time on reading codes between versions - checking bugs and further investigation (especially for new team members). 

On the specific, I'm referring to a specific upgrade between `0.8.x` to `1.x` but it should be released as well as for future upgrade
in order to upgrade the operator we must migrate the agent as well: 
https://github.com/DataDog/helm-charts/tree/datadog-3.25.1/charts/datadog-operator#migrating-to-the-version-10-of-the-datadog-operator

**Comment by CharlyF** [comment]
Hi @nicolodallavalentinaclearscore - Thank you very much for opening this up.
I completely understand and will get to this now. We did a guide in the docs here https://github.com/DataDog/datadog-operator/blob/main/docs/v2alpha1_migration.md
I will link up to this and we will take another step at adding more details, let me know if that sounds good for you.

Out of curiosity, how did the migration process go for you?

**Comment by CharlyF** [comment]
We just merged the doc update, I will close this for now but please let us know how your migration goes @nicolodallavalentinaclearscore.

**Comment by nicolodallavalentinaclearscore** [comment]
@CharlyF We completed the migration with success. Very helpful the helm process and I love the manifest migration API for the Datadog's agent. It saves me a lot of time. Thanks again for the docs update
