### ISSUE TITLE
Enabling Cluster Checks Runner doesn't get the orchestrator and kube_state_core checks dispatched to the runners

### ISSUE THREAD

**Issue by arapulido** [DataDog/datadog-operator#809]
**Describe what happened:**

I am running Operator 1.0.2 in a 1.27 cluster

Running the Node Agents and DCA. Cluster Checks runners are not yet enabled. The `orchestrator` and `kube_state_core` checks are being run by the DCA.

Edit the `DatadogAgent` definition to enable cluster checks runners.

Expected results:

* Once the cluster-checks-runner pod is running, the DCA reschedules the checks to the cluster checks runner

Actual results:

* The DCA continues to run those checks
* If I kill the DCA pod and it restarts, then the checks are correctly considered cluster checks and dispatched to the Cluster checks runner.

Maybe the Operator should restart the DCA if the cluster checks runners are enabled?

**Steps to reproduce the issue:**

1. Deploy the Agents using the Operator
2. Once the checks are running, edit the `DatadogAgent` definition to enable cluster checks runners

**Comment by CharlyF** [comment]
Thanks for opening this up!
I added a card to our next sprint to address this.

**Comment by levan-m** [comment]
This was resolved in 1.1.0.
