### ISSUE TITLE
Labels not propagated to Datadog Agent in Pod Template Spec

### ISSUE THREAD

**Issue by ylee-figma** [DataDog/datadog-operator#813]
**Describe what happened:**

Including `labels` in CRD doesn't propagate pod labels for nodeAgent.

**Describe what you expected:**

Including `labels` in CRD doesn't propagates pod labels for nodeAgent.

Code: https://github.com/DataDog/datadog-operator/blob/bd749fdd6d26ec02b5fb0cbec155d7b994c00528/controllers/datadogagent/component/agent/default.go#L44-L61

**Steps to reproduce the issue:**

Edit DatadogAgent CRD `override.nodeAgent.labels`. Describe datadog-agent daemonset and see that there is no label propagated to template spec

**Comment by CharlyF** [comment]
Hi there - Thank you for reporting this.
I added a card to our backlog to investigate. Could you confirm if you applied the DatadogAgent with the override to configure the labels or if you had the daemonset deployed and then edited the DatadogAgent with the override but did not see the resulting rollout?

**Comment by fanny-jiang** [comment]
Hi @ylee-figma, I'm following up on whether you've seen Charly's above question? Please let us know the answers to his questions as it'll be very helpful to have additional context regarding your issue.

Did you re-deploy the v2alpha1 DatadogAgent CRD after making the edits? E.g. `kubectl apply -f datadogagent.yaml`
The datadog-operator will reconcile configuration changes to the `DatadogAgent` CRD after the resource is applied again. 

I tried reproducing the problem myself and I'm seeing the configured labels as expected. I'm using the datadog/datadog-operator v1.0.3 chart and tested with K8s version v1.23.17 and v1.24.7.
