### ISSUE TITLE
Feature Request: Add support to use notify_by

### ISSUE THREAD

**Issue by cmotta2016** [DataDog/datadog-operator#814]
The Datadog operator doesn't support `notify_by` options. It would be great if we have this support.

```json
"notify_by": [
	"cluster_name",
	"kube_namespace"
],
```

**Comment by willianccs** [comment]
Just for help this option exists on terraform-provider-datadog:
> [notify_by](https://registry.terraform.io/providers/DataDog/datadog/latest/docs/resources/monitor#notify_by) (Set of String) Controls what granularity a monitor alerts on. Only available for monitors with groupings. For instance, a monitor grouped by `cluster`, `namespace`, and `pod` can be configured to only notify on each new cluster violating the alert conditions by setting **notify_by to ['cluster']**. Tags mentioned in `notify_by` must be a subset of the grouping tags in the query. For example, a query grouped by cluster and namespace cannot notify on region. Setting notify_by to [*] configures the monitor to notify as a simple-alert

**Comment by CharlyF** [comment]
Hi folks - Thank you for bringing this up to our attention. 
I added this to our backlog and we will report back when we review it.
