### ISSUE TITLE
Feature Request: Add support for notification_preset_name

### ISSUE THREAD

**Issue by cmotta2016** [DataDog/datadog-operator#815]
It would be great if the Datadog operator have support for `notification_preset_name`:

```json
"notification_preset_name": "hide_query"
```

**Comment by CharlyF** [comment]
Hi - Thank you for making this feature request. I added it to our backlog and we will report back when we review it/work on it.

**Comment by bakayolo** [comment]
Any updates on this, this is currently blocking us from integrating with discord webhooks because of the content that messes up with the payload.

**Comment by celenechang** [comment]
Closing as this was released in 1.4.0
