### ISSUE TITLE
datadog operator crd missing options

### ISSUE THREAD

**Issue by fdmota** [DataDog/datadog-operator#833]
Datadog operator does not support yet datadog monitor options like `restrictionQuery`, `groupbySimpleMonitor` or `renotifyOccurrences`. When can we expect this to be added?

**Comment by khewonc** [comment]
Hi, thanks for reaching out. I'll add a card in our backlog to add those fields to the DatadogMonitor CRD. We'll report back here with any updates on this

**Comment by levipe01** [comment]
Hi @fdmota, in regards to the `restrictionQuery` option are you referring to the endpoint described below?

https://docs.datadoghq.com/api/latest/logs-restriction-queries/

If so, this is currently in public beta so this is not something that we would add until it is GA. That said, can you provide an example of your use case for this including how you currently use this in conjunction with your monitors so we can look into possibly adding this in the future?

**Comment by levipe01** [comment]
Hi, we have added the `groupbySimpleMonitor` and `renotifyOccurrences` configuration and they will be available in v1.6 of the Operator. If you still require a configuration for `restrictionQuery` please open up a new issue and provide more details on your use case there.
