### ISSUE TITLE
Pod Disruption Budget isn't created for cluster agent

### ISSUE THREAD

**Issue by ylee-figma** [DataDog/datadog-operator#864]
**Output of the info page (if this is a bug)**
```
❯ k get datadogagents.datadoghq.com
NAME      AGENT             CLUSTER-AGENT     CLUSTER-CHECKS-RUNNER   AGE
datadog   Running (4/4/4)   Running (2/2/2)                           76d

❯ k get pdb -A | rg cluster

```

**Describe what happened:**
If the replica count is above 1, then PDB should be created according to this logic: https://github.com/DataDog/datadog-operator/blob/2b77d724bd06c256106fe45c54f9a90ddaa2fb8b/controllers/datadogagent/poddisruptionbudget.go#L40

However, maybe because the apiVersion changed on the agent, it's not creating PDBs.

**Describe what you expected:**
PDB for cluster agent to be created

**Steps to reproduce the issue:**
Scale up replica of cluster agent to 2.

**Additional environment details (Operating System, Cloud provider, etc):**

**Comment by levan-m** [comment]
Hello,

Thanks for submitting the issue! You are right `0.8.x` managed PDB for both Cluster Agent and Cluster Checks Runners, this isn't yet supported in `1.x.x`, fact highlighted [here](https://github.com/DataDog/datadog-operator#migrating-from-08x-to-100). We haven't prioritized this for the upcoming `1.1.0`, we may be able to do it for the next one.

**Comment by jalaziz** [comment]
Coming from the helm chart installation method, I noticed this was missing too.

**Comment by tbavelier** [comment]
Completed in https://github.com/DataDog/datadog-operator/pull/1454, will be part of 1.11.x release
