### ISSUE TITLE
datadog-operator not creating clusterrole "datadog-datadog-orch-exp-dca" 

### ISSUE THREAD

**Issue by siva-kommireddy** [DataDog/datadog-operator#895]
**Output of the info page (if this is a bug)**
```
2023-08-17 16:46:33 UTC | CLUSTER | WARN | (client-go@v0.23.15/tools/cache/reflector.go:324 in func1) | pkg/mod/k8s.io/client-go@v0.23.15/tools/cache/reflector.go:167: failed to list *v1.RoleBinding: rolebindings.rbac.authorization.k8s.io is forbidden: User "system:serviceaccount:datadog:datadog-cluster-agent" cannot list resource "rolebindings" in API group "rbac.authorization.k8s.io" at the cluster scope

2023-08-17 16:46:33 UTC | CLUSTER | ERROR | (apimachinery@v0.23.15/pkg/util/runtime/runtime.go:108 in HandleError) | pkg/mod/k8s.io/client-go@v0.23.15/tools/cache/reflector.go:167: Failed to watch *v1.RoleBinding: failed to list *v1.RoleBinding: rolebindings.rbac.authorization.k8s.io is forbidden: User "system:serviceaccount:datadog:datadog-cluster-agent" cannot list resource "rolebindings" in API group "rbac.authorization.k8s.io" at the cluster scope
```

**Describe what happened:**
Datadog Operator is not creating the cluster role "datadog-datadog-orch-exp-dca" which is causing the Datadog Cluster(Orchestrator) Overview UI showing banner message stating "installation required" and the pop-up shows health status of Orchestrator as "Partial".

After manually creating the ClusterRole "datadog-datadog-orch-exp-dca", Datadog-operator was able to create the `ClusterRoleBinding` by linking ServiceAccount "datadog-cluster-agent" and ClusterRole "datadog-datadog-orch-exp-dca". After this change, cluster entry was reporting in DD Cluster Overview UI and also the error message listed above no longer showing up in Datadog-cluster-agent pod logs

**Describe what you expected:**
Expecting to see the cluster entry in Datadog Cluster overview after installing Datadog on the cluster. Instead, the cluster entry is missing and a banner message is present stating "installation required" with Orchestrator state being listed as "Partial"

**Steps to reproduce the issue:**
Deploying datadog using Datadog-operator(v1.1.0) method with latest dd-agent version on K8 cluster running v1.25.6

**Additional environment details (Operating System, Cloud provider, etc):**

Cloud Provider: AKS
Operating System: Ubuntu 22.4
K8s Version: 1.25.6
Datadog Operator: v1.1.0
Datadog Agent: v7.46.0
Datadog Cluster-agent: v7.46.0

**Comment by khewonc** [comment]
Hi @siva-kommireddy , thanks for reaching out. What version of the [datadog-operator helm chart](https://github.com/DataDog/helm-charts/tree/main/charts/datadog-operator) are you using? Running `helm list -n <namespace>` should have that info.

**Comment by siva-kommireddy** [comment]
Here's the current version of helm chat use for Datadog-operator 
```
NAME            	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART                 	APP VERSION
datadog-operator	datadog  	1       	2023-08-17 17:03:23.487979687 +0000 UTC	deployed	datadog-operator-1.0.2	1.0.0
```

**Comment by khewonc** [comment]
@siva-kommireddy  Thanks for the extra info. Could you update your local charts by running `helm repo update` and then [updating your release](https://helm.sh/docs/helm/helm_upgrade/) to use the latest `1.1.0` version of the `datadog-operator` helm chart? You should see `1.1.0` in the `CHART` and `APP VERSION` when running the same `helm list` command from before. 

I believe the `datadog-operator` chart is missing some permissions that it needs to grant the cluster agent for the orchestrator explorer feature, which is causing the missing `datadog-datadog-orch-exp-dca` ClusterRole. There should be an error similar to `xxx is attempting to grant RBAC permissions not currently held` in the operator pod logs if this is the case. Those permissions were added in `1.0.3` of the operator chart, so updating to the current latest version, `1.1.0`, should include them.

**Comment by siva-kommireddy** [comment]
@khewonc After using the latest chart version `1.1.0`, datadog deployment was successful and all necessary roles and rolebindings are properly created. Thanks for your assistance.

**Comment by khewonc** [comment]
Glad to hear that worked! I'll close this out, but feel free to reach out if you've got any other questions or issues
