### ISSUE TITLE
Overrides for security agent container

### ISSUE THREAD

**Issue by paulkirby-hotjar** [DataDog/datadog-operator#898]
Right now, we can add overrides to the CRD that work for cluster agent, node agent, and the cluster checks runner. We need to be able to add overrides for the security agent as well (and ideally, all containers involved) so we can configure the security agent to send logs to our observability pipeline worker rather than directly to DD. Is this something that could be added?

**Comment by fanny-jiang** [comment]
Hi @paulkirby-hotjar, security-agent container overrides can be configured with the key `spec.override.nodeAgent.containers.security-agent`. 

If that doesn't work, can you please share an example snippet of the security-agent overrides configuration and the specific fields that you are trying to override?

**Comment by paulkirby-hotjar** [comment]
Thanks @fanny-jiang - turns out the issue isn't with the CRD but with the agent not configuring the security agent for vector properly. We'll move this issue over to their repo. Thanks for the response!
