### ISSUE TITLE
Increase of logs Tx bytes after upgrading

### ISSUE THREAD

**Issue by mcatany** [DataDog/datadog-operator#907]
One month ago we upgraded our operator from 0.8.0 to 1.0.3 (so we migrated to v2alpha1 CRD)  and our dd-agent and dd-cluster-agent from 7.43.1 to 7.46.0. Since that same day (7th of August) we can see and increase of datadog logs bytes and increase of network transmitted bytes from our datadog daemonsets in our Kubernetes cluster.ç![image](https://github.com/DataDog/datadog-operator/assets/40259268/7c075ddd-5ddf-4848-b052-cc54a6ead3f3)
![image](https://github.com/DataDog/datadog-agent/assets/40259268/c4e54fad-45d6-4adb-9ac4-fe6b03d5f7ce)
![image](https://github.com/DataDog/datadog-agent/assets/40259268/ee8bf9ab-f2eb-474f-9d6d-a8b58e5f62d3)

We don't see the same increase on logs events:
![image](https://github.com/DataDog/datadog-agent/assets/40259268/83cb4c23-6fd9-4ac2-8aaa-88620833f7ba)

Does it make any sense?

**Comment by celenechang** [comment]
Thanks for reporting @mcatany . Do you mind opening a support ticket so we can investigate? It would be most helpful if you could pass along a [flare](https://docs.datadoghq.com/agent/troubleshooting/send_a_flare/?tab=agentv6v7) from the cluster agent and a flare from the node agent.
