### ISSUE TITLE
How to migrate from Datadog Helm Chart

### ISSUE THREAD

**Issue by dschniepp** [DataDog/datadog-operator#919]
We used the `datadog` Helm Chart to deploy our Datadog agent. Though we want to migrate to the datadog-operator. Unfortunately the configuration parameters of the values.yaml and the options in the `DatadogAgent` do not match. Is there a migration guide available or another option in how to migrate it?

**Comment by khewonc** [comment]
Hi, thanks for reaching out. We don't have a set process to get helm values.yaml migrated automatically to a DatadogAgent manifest, but most of the options available in the Datadog helm chart should be available or configurable in a DatadogAgent manifest. If there are certain fields you're having trouble migrating over, please let us know or [reach out to our support team](http://help.datadoghq.com/) and we'll look into it.

**Comment by dschniepp** [comment]
Thanks, that's how I proceeded.
