### ISSUE TITLE
Feature request:  add support for metrics tag cardinality under dogstatsd

### ISSUE THREAD

**Issue by jcogilvie** [DataDog/datadog-operator#929]
The operator supports a flag for `dogstatsd.originDetectionEnabled` but misses one other recommended point of configuration for this case:

Dogstatsd documentation recommends us to [set](https://docs.datadoghq.com/developers/dogstatsd/unix_socket/?tab=kubernetes#origin-detection) `DD_DOGSTATSD_TAG_CARDINALITY` as well.  This should be added as a field under the dogstatsd feature.

This is desirable because as a string enum field, the operator/CRD could provide an extra layer of validation.

**Comment by CharlyF** [comment]
Hi @jcogilvie - Thanks for opening this up. I am adding it to our backlog.

**Comment by tbavelier** [comment]
Closing as it was added in https://github.com/datadog/datadog-operator/pull/936 (available in `1.3.0`)
