### ISSUE TITLE
[Question] Supporting {{#is_alert}} to skip the recovery alert

### ISSUE THREAD

**Issue by haphamdev** [DataDog/datadog-operator#937]
I want to have alert when a certain log appears in the last 5m and do not want a recovery alert 5m after that.
We can do that in DataDog by adding `{{#is_alert}}` to the alert message. For example:
```
{{#is_alert}}
Purchase failed because of payment failure
@slack-alert_purchase_failure
{{/is_alert}}
```

**Describe what happened:**
1. I cannot add `{{#is_alert}}` to helm resource.

```
  message: |
    {{\#is_alert}}
    Purchase failed because of payment failure
    @slack-alert_purchase_failure
    {{/is_alert}}
  {{ end }}
```
Error: `[ERROR] templates/: parse error at (.../templates/alerts.yaml:213): unexpected "#" in command`

2. Try surrounding by double-quotes 
```
  message: |
    "{{\#is_alert}}"
    Purchase failed because of payment failure
    @slack-alert_purchase_failure
    "{{/is_alert}}"
  {{ end }}
```
Same error: `[ERROR] templates/: parse error at (.../templates/alerts.yaml:213): unexpected "#" in command`

3. No escaping `#`
```
  message: |
    {{#is_alert}}
    Purchase failed because of payment failure
    @slack-alert_purchase_failure
    {{/is_alert}}
  {{ end }}

```
Error: `[ERROR] templates/: parse error at (.../templates/alerts.yaml:213): unexpected "#" in command`

4. Try surrounding by single-quotes
```
  message: |
    '{{#is_alert}}'
    Purchase failed because of payment failure
    @slack-alert_purchase_failure
    '{{/is_alert}}'
  {{ end }}
```
Same error: `[ERROR] templates/: parse error at (.../templates/alerts.yaml:213): unexpected "#" in command`

Is it possible?

**Comment by celenechang** [comment]
Hi @haphamdev ,

Thanks for reporting. I tried to reproduce your issue but was able to successfully create a monitor with the following spec:

```
spec:
  query: "avg(last_10m):avg:system.disk.in_use{*} by {host} > 0.5"
  type: "metric alert"
  name: "Test monitor made from DatadogMonitor"
  message: |
    {{#is_alert}}
    Purchase failed because of payment failure
    @slack-alert_purchase_failure
    {{/is_alert}}
```

I created the monitor using `kubectl apply -f <file_name.yaml>` . Are you using the same method?

**Comment by levan-m** [comment]
Hi @haphamdev, I see you go a response on escaping `{{` in the Helm templates. Did this solve your issue?

**Comment by haphamdev** [comment]
Yes, I can solve it like this
```
{{ "{{#is_alert}}" }}
```
