### ISSUE TITLE
Allow skipping cert validation for openmetrics endpoints

### ISSUE THREAD

**Issue by relaxdiego** [DataDog/datadog-operator#952]
**Describe what happened:**

I'm trying to get `datadog-agent` to scrape the metrics from KubeVirt's `virt-handler` component. However, because (A) `virt-handler` only exposes metrics over HTTPS using a self-signed certificate and (B) `datadog-agent` always wants to validate said certificate, I get the following error from `agent status`

```
    openmetrics (3.0.2)
    -------------------
      Instance ID: openmetrics:kubevirt:b304a8fb1d85cc02 [ERROR]
      Configuration Source: container:containerd://d71bb19637d2fcca2a6381e333934ba2a134f17372229198999bb322374b0258
      Total Runs: 5
      Metric Samples: Last Run: 0, Total: 0
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 1, Total: 5
      Average Execution Time : 38ms
      Last Execution Date : 2023-10-18 23:19:18 UTC (1697671158000)
      Last Successful Execution Date : Never
      Error: There was an error scraping endpoint https://192.168.22.138:8443/metrics: HTTPSConnectionPool(host='192.168.22.138', port=8443): Max retries exceeded with url: /metrics (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))
      Traceback (most recent call last):
        File "/opt/datadog-agent/embedded/lib/python3.9/site-packages/datadog_checks/base/checks/base.py", line 1142, in run
          self.check(instance)
        File "/opt/datadog-agent/embedded/lib/python3.9/site-packages/datadog_checks/base/checks/openmetrics/v2/base.py", line 67, in check
          raise_from(type(e)("There was an error scraping endpoint {}: {}".format(endpoint, e)), None)
        File "<string>", line 3, in raise_from
      requests.exceptions.SSLError: There was an error scraping endpoint https://192.168.22.138:8443/metrics: HTTPSConnectionPool(host='192.168.22.138', port=8443): Max retries exceeded with url: /metrics (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))

```

**Describe what you expected:**

I was hoping for there to be an option to tell `datadog-agent` not to validate the other end's certificate but nothing in the docs indicate that's possible.

**Steps to reproduce the issue:**

1. Deploy Datadog
2. Deploy KubeVirt Operator
3. Edit the `KubeVirt` resource such that the following, which adds Datadog's AD v2 annotations to `virt-handler`, is present under `spec`:

```yaml
  customizeComponents:
    patches:
      - resourceType: Daemonset
        resourceName: virt-handler
        patch: '{"spec":{"template":{"metadata":{"annotations":{"ad.datadoghq.com/virt-handler.checks":"{\n  \"openmetrics\": {\n    \"init_config\": {},\n    \"instances\": [\n      {\n        \"openmetrics_endpoint\": \"https://%%host%%:8443/metrics\",\n        \"namespace\": \"kubevirt\",\n        \"metrics\": [\"kubevirt_vmi_*\"]\n      }\n    ]\n  }\n}\n"}}}}}'
        type: strategic
```

4. Deploy KubeVirt

**Additional environment details (Operating System, Cloud provider, etc):**

Datadog agent version: gcr.io/datadoghq/agent:7.47.1
KubeVirt virt-handler version: quay.io/kubevirt/virt-handler:v1.0.0
Kubernetes version: v1.28.2-eks-f8587cb

**Comment by khewonc** [comment]
@relaxdiego Could you try adding [tls_verify: false](https://github.com/DataDog/integrations-core/blob/106cc882386bf0a54eef19b73d336f22a9508775/openmetrics/datadog_checks/openmetrics/data/conf.yaml.example#L489) to your openmetrics check to see if that helps?

**Comment by relaxdiego** [comment]
Thanks, @khewonc. I should've mentioned that I did try that setting and it did not help.

**Comment by khewonc** [comment]
@relaxdiego Thanks for trying that out. Would you mind opening up a [support ticket](https://docs.datadoghq.com/help/) and sending a flare from the agent so the team can take a further look into it?

**Comment by relaxdiego** [comment]
Apologies for the late reply. It appears to be working now. I must've placed the `tls_verify` parameter in the wrong place.

```
openmetrics (3.0.2)
-------------------
  Instance ID: openmetrics:kubevirt:f4c7c45c2de59ec4 [OK]
  Configuration Source: container:containerd://fa77be90714a4952658c1a66cacee2b0ef2add10591d0473fe18f3aad0489a62
  Total Runs: 8
  Metric Samples: Last Run: 477, Total: 3,816
  Events: Last Run: 0, Total: 0
  Service Checks: Last Run: 1, Total: 8
  Average Execution Time : 129ms
  Last Execution Date : 2023-11-16 01:41:24 UTC (1700098884000)
  Last Successful Execution Date : 2023-11-16 01:41:24 UTC (1700098884000)
```

Closing this issue.
