### ISSUE TITLE
Feature Request: Global environment variable configuration

### ISSUE THREAD

**Issue by jalaziz** [DataDog/datadog-operator#961]
The datadog helm chart installation has a top-level `datadog.env` configuration option which sets environment variables across all agents. It would be great if a similarly global option existed for the agent configuration CRD.

This can be particularly helpful for setting variables like `DD_EC2_PREFER_IMDSV2`.

Without it, the variable has to be set for each component which can redundant and error-prone.

**Comment by swang392** [comment]
Hi @jalaziz! Thanks for bringing this to our attention. We've added this functionality in v1.10 -- let us know if you encounter any issues with it!
