### ISSUE TITLE
What are the default resources (limits / requests) for each container

### ISSUE THREAD

**Issue by pellizzetti** [DataDog/datadog-operator#982]
I'm overriding the resources for each container as shown [here](https://github.com/DataDog/datadog-operator/blob/0b5857932b1735bf493f5e5d8ff0746cb98e44aa/docs/configuration.v2alpha1.md#override), but I'm curious, what are the default resources values for these containers?

I skimmed through the code, and looking at the `NewDefaultAgentPodTemplateSpec` and `defaultPodSpec` methods, it seems that the resources aren't being set, is that right?

**Comment by levan-m** [comment]
Hello,

You right, we don't set default limits in Operator or Agent Helm chart [values.yaml](https://github.com/DataDog/helm-charts/blob/896a355268ff6b3cfd33f945ae373912caa8b6e4/charts/datadog/values.yaml#L1441-L1448).
